version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: microjustice_db
    restart: always
    environment:
      POSTGRES_DB: microjustice
      POSTGRES_USER: nikhil
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

